import { ProductoInterface } from '../../core/interfaces/producto.interface';

export class TecnologiaConstants {
  
  public static PRODUCTOS: Array<ProductoInterface> = [
    {
      idProducto: 1001,
      nombreImg: 'galaxys10.jpg', 
      nombreCategoria: 'Samsung',
      nombreProducto: 'Samsung galaxy s10',
      descripcionProducto: '6 GB RAM + 128 gb almacenamiento + 5000 mah + full hd',
      precioProducto: 1599,
      cantidadProducto: 0,
    }, 
    {
      idProducto: 1002,
      nombreImg: 'galaxynote20.jpg', 
      nombreCategoria: 'Samsung',
      nombreProducto: 'Samsung galaxy note20',
      descripcionProducto: '8 GB RAM + 256 gb almacenamiento + 6000 mah + full hd',
      precioProducto: 2499,
      cantidadProducto: 0,
    }, 
    {
      idProducto: 1003,
      nombreImg: 'motog9.jpg', 
      nombreCategoria: 'Motorola',
      nombreProducto: 'Motorola g9 plus',
      descripcionProducto: '3 GB RAM + 64 gb almacenamiento + 3500 mah + full hd',
      precioProducto: 999,
      cantidadProducto: 0,
    }, 
    {
      idProducto: 1004,
      nombreImg: 'motog7power.jpg', 
      nombreCategoria: 'Motorola',
      nombreProducto: 'Motorola g7 power',
      descripcionProducto: '3 GB RAM + 64 gb almacenamiento + 4500 mah + hd',
      precioProducto: 899,
      cantidadProducto: 0,
    }, 
    {
      idProducto: 1005,
      nombreImg: 'samsungtv50.jpg', 
      nombreCategoria: 'Samsung tv',
      nombreProducto: 'Samsung tv 50"',
      descripcionProducto: 'Full hd + puerto hdmi + magic control',
      precioProducto: 1899,
      cantidadProducto: 0,
    }, 
    {
      idProducto: 1006,
      nombreImg: 'samsungtv65.jpg', 
      nombreCategoria: 'SamsungTv',
      nombreProducto: 'Samsung tv 65"',
      descripcionProducto: 'Ultra hd 4k + pantalla cristal + magic control',
      precioProducto: 2899,
      cantidadProducto: 0,
    }, 
    {
      idProducto: 1007,
      nombreImg: 'samsungtv70.jpg', 
      nombreCategoria: 'SamsungTv',
      nombreProducto: 'Samsung tv 70"',
      descripcionProducto: 'Ultra hd + 2 puertos hdmi + conxion bluetooh',
      precioProducto: 2659,
      cantidadProducto: 0,
    }, 
    {
      idProducto: 1008,
      nombreImg: 'daeewotv.jpg', 
      nombreCategoria: 'DaeewooTv',
      nombreProducto: 'Daeewoo tv 49"',
      descripcionProducto: 'Pantalla full hd + wifi + samart tv',
      precioProducto: 899,
      cantidadProducto: 0,
    }, 
    {
      idProducto: 1009,
      nombreImg: 'laptophpgaming.jpg', 
      nombreCategoria: 'Asus',
      nombreProducto: 'Laptop gaming asus',
      descripcionProducto: '16gb ram + 1tb ssd + full hd',
      precioProducto: 7999,
      cantidadProducto: 0,
    }, 
    {
      idProducto: 1010,
      nombreImg: 'macbookair.jpg', 
      nombreCategoria: 'Apple',
      nombreProducto: 'Macbook air ',
      descripcionProducto: '8 gb ram + 500 ssd + bluetooh',
      precioProducto: 1899,
      cantidadProducto: 0,
    }, 
    {
      idProducto: 1011,
      nombreImg: 'laptophp15.jpg"', 
      nombreCategoria: 'HP',
      nombreProducto: 'Laptop hp 15"',
      descripcionProducto: '8gb ram + 1 tb ssd + full hd',
      precioProducto: 2600,
      cantidadProducto: 0,
    }, 
    {
      idProducto: 1012,
      nombreImg: 'laptoplg.jpg', 
      nombreCategoria: 'LG',
      nombreProducto: 'Laptop lg',
      descripcionProducto: '12 GB RAM + 528 gb almacenamiento + uhd 4k',
      precioProducto: 2589,
      cantidadProducto: 0,
    },
  ];
  
}