import { ProductoInterface } from '../../core/interfaces/producto.interface';

export class ModaConstants {
  
  public static PRODUCTOS: Array<ProductoInterface> = [
    {
    idProducto: 1001,
    nombreImg: 'carnivalxl.jpg', 
    nombreCategoria: 'Sombras',
    nombreProducto: 'Carnival xl',
    descripcionProducto: 'Paleta de sombras 40 tonos de diversos colores',
    precioProducto: 350,
    cantidadProducto: 0,
  },
  {
    idProducto: 1002,
    nombreImg: 'nars.jpg', 
    nombreCategoria: 'Base',
    nombreProducto: 'Nars',
    descripcionProducto: 'Base de maquillaje de larga duracion con alta cobertura',
    precioProducto: 100,
    cantidadProducto: 0,
  },
  {
    idProducto: 1003,
    nombreImg: 'casaca.jpg', 
    nombreCategoria: 'Casacas',
    nombreProducto: 'Casaca de cuero mujer',
    descripcionProducto: 'Casaca de cuero color negro , doble cara .',
    precioProducto: 400,
    cantidadProducto: 0,
  },
  {
    idProducto: 1005,
    nombreImg: 'barclayjeans.jpg', 
    nombreCategoria: 'Jean',
    nombreProducto: 'Jean mujer cullote',
    descripcionProducto: 'Jean clasico con material 100% algodon',
    precioProducto: 129,
    cantidadProducto: 0,
  },
  {
    idProducto: 1007,
    nombreImg: 'setdeanillos.jpg', 
    nombreCategoria: 'Anillos',
    nombreProducto: 'Twint set',
    descripcionProducto: 'Anillo rose de 3 mm en plata de 925 + juego de aretes',
    precioProducto: 199,
    cantidadProducto: 0,
  },
  {
    idProducto: 1009,
    nombreImg: 'sunglassesaesthetic.jpg', 
    nombreCategoria: 'Lentes',
    nombreProducto: 'Lentes de sol',
    descripcionProducto: 'lentes con proteccion uv + estuche + audifonos',
    precioProducto: 399,
    cantidadProducto: 0,
  },
  {
    idProducto: 1011,
    nombreImg: 'reloj.jpg', 
    nombreCategoria: 'Reloj',
    nombreProducto: 'Reloj de mujer',
    descripcionProducto: 'Fino reloj dolcce & gabanna',
    precioProducto: 999,
    cantidadProducto: 0,
  },
  {
    idProducto: 1012,
    nombreImg: 'sandalias.jpg', 
    nombreCategoria: 'Sandalias',
    nombreProducto: 'Sandalias de verano',
    descripcionProducto: 'Lindas sandalias color camello',
    precioProducto: 399,
    cantidadProducto: 0,
  },
  {
    idProducto: 1004,
    nombreImg: 'arete.jpg', 
    nombreCategoria: 'Aretes',
    nombreProducto: 'Aretes de plata',
    descripcionProducto: 'Aretes con acabados en plata de diferentes modelos',
    precioProducto: 89,
    cantidadProducto: 0,
  },
  {
    idProducto: 1006,
    nombreImg: 'bota.jpg', 
    nombreCategoria: 'Botas',
    nombreProducto: 'Botas de cuero',
    descripcionProducto: 'Botas de cuero de piel de lagarto con finos acabados',
    precioProducto: 999,
    cantidadProducto: 0,
  },
  {
    idProducto: 1008,
    nombreImg: 'sombrero.jpg', 
    nombreCategoria: 'Sombrero',
    nombreProducto: 'Sombrero moderno de playa',
    descripcionProducto: 'Lindo sombrero con excelentes acabados',
    precioProducto: 150,
    cantidadProducto: 0,
  },
  {
    idProducto: 1010,
    nombreImg: 'labial.jpg', 
    nombreCategoria: 'Labial',
    nombreProducto: 'Labial mate',
    descripcionProducto: 'Sabor fresa y extra duracion',
    precioProducto: 50,
    cantidadProducto: 0,
    },
  ];
}